package fr.wezord.main.init;

import fr.wezord.main.References;
import fr.wezord.main.item.ArmorMod;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = References.MODID)
public class ArmorsMod {
	
	public static ArmorMaterial armor = EnumHelper.addArmorMaterial("armorbase", References.MODID + ":armorbase", 14, 
			new int[] {0, 0, 0, 0}, 15, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 0.0F);
	
	public static Item armorbase;
	public static Item Ac_Necklace01;
	public static Item Ac_Necklace02;
	public static Item Ac_Necklace03;
	public static Item Ac_Necklace04;
	public static Item Ac_Ring04;
	public static Item icon_15;
	public static Item icon_16;
	public static Item icon_17;
	public static Item icon_18;
	public static Item icon_19;
	public static Item icon_20;
	public static Item icon_21;
	public static Item icon_22;
	public static Item icon_23;
	public static Item icon_24;
	public static Item icon_25;
	public static Item icon_27;
	public static Item icon_28;
	public static Item necklace_01a;
	public static Item necklace_01b;
	public static Item necklace_01c;
	public static Item necklace_01d;
	public static Item master_jewel;
	public static Item mithril_jewel;
	public static Item trilogy_jewel;
	public static Item adamant_jewel;
	public static Item amulette1;
	public static Item amulette2;
	public static Item amulette3;
	public static Item amulette4;
	public static Item amulette5;
	public static Item amulette6;
	public static Item amulette7;
	public static Item amulette8;
	public static Item amulette9;
	public static Item amulette10;
	public static Item amulette11;
	public static Item amulette12;
	public static Item amulette13;
	public static Item amulette14;
	public static Item amulette15;
	public static Item amulette16;
	public static Item amulette17;
	public static Item amulette18;
	public static Item amulette19;
	public static Item amulette20;
	public static Item amulette21;
	public static Item amulette22;
	public static Item amulette23;
	public static Item amulette24;
	public static Item amulette25;
	public static Item amulette26;
	public static Item amulette27;
	public static Item amulette28;
	public static Item amulette29;
	public static Item amulette30;
	public static Item amulette31;
	public static Item amulette32;
	public static Item amulette33;
	public static Item amulette34;
	public static Item amulette35;
	public static Item amulette36;
	public static Item amulette37;
	public static Item amulette38;
	public static Item amulette39;
	public static Item amulette40;
	public static Item anneau1;
	public static Item anneau2;
	public static Item anneau3;
	public static Item anneau4;
	public static Item anneau5;
	public static Item anneau6;
	public static Item anneau7;
	public static Item anneau8;
	public static Item anneau9;
	public static Item anneau10;
	public static Item anneau11;
	public static Item anneau12;
	public static Item anneau13;
	public static Item anneau14;
	public static Item anneau15;
	public static Item anneau16;
	public static Item anneau17;
	public static Item anneau18;
	public static Item anneau19;
	public static Item anneau20;
	public static Item anneau21;
	public static Item anneau22;
	public static Item anneau23;
	public static Item anneau24;
	public static Item anneau25;
	public static Item anneau26;
	public static Item anneau27;
	public static Item anneau28;
	public static Item anneau29;
	public static Item anneau30;
	public static Item anneau31;
	public static Item anneau32;
	public static Item anneau33;
	public static Item anneau34;
	public static Item anneau35;
	public static Item anneau36;
	public static Item anneau37;
	public static Item anneau38;
	public static Item anneau39;
	public static Item armurelegere1;
	public static Item armurelegere2;
	public static Item armurelegere3;
	public static Item armurelegere4;
	public static Item armurelegere5;
	public static Item armurelegere6;
	public static Item armurelegere7;
	public static Item armurelegere8;
	public static Item armurelegere9;
	public static Item armurelegere10;
	public static Item armurelegere11;
	public static Item armurelegere12;
	public static Item armurelegere13;
	public static Item armurelegere14;
	public static Item armurelegere15;
	public static Item armurelegere16;
	public static Item armurelegere17;
	public static Item armurelegere18;
	public static Item armurelegere19;
	public static Item armurelegere20;
	public static Item armurelegere21;
	public static Item armurelegere22;
	public static Item armurelegere23;
	public static Item armurelegere24;
	public static Item armurelegere25;
	public static Item armurelegere26;
	public static Item armurelegere27;
	public static Item armurelegere28;
	public static Item armurelegere29;
	public static Item armurelegere30;
	public static Item armurelegere31;
	public static Item armurelourde1;
	public static Item armurelourde2;
	public static Item armurelourde3;
	public static Item armurelourde4;
	public static Item armurelourde5;
	public static Item armurelourde6;
	public static Item armurelourde7;
	public static Item armurelourde8;
	public static Item armurelourde9;
	public static Item armurelourde10;
	public static Item armurelourde11;
	public static Item armurelourde12;
	public static Item armurelourde13;
	public static Item armurelourde14;
	public static Item armurelourde15;
	public static Item armurelourde16;
	public static Item armurelourde17;
	public static Item armurelourde18;
	public static Item armurelourde19;
	public static Item armurelourde20;
	public static Item armurelourde21;
	public static Item armurelourde22;
	public static Item armurelourde23;
	public static Item armurelourde24;
	public static Item armurelourde25;
	public static Item armurelourde26;
	public static Item armurelourde27;
	public static Item armurelourde28;
	public static Item armurelourde29;
	public static Item armurelourde30;
	public static Item armuremagique1;
	public static Item armuremagique2;
	public static Item armuremagique3;
	public static Item armuremagique4;
	public static Item armuremagique5;
	public static Item armuremagique6;
	public static Item armuremagique7;
	public static Item armuremagique8;
	public static Item armuremagique9;
	public static Item armuremagique10;
	public static Item armuremagique11;
	public static Item armuremagique12;
	public static Item armuremagique13;
	public static Item armuremagique14;
	public static Item armuremagique15;
	public static Item armuremagique16;
	public static Item armuremagique17;
	public static Item armuremagique18;
	public static Item armuremagique19;
	public static Item armuremagique20;
	public static Item armuremagique21;
	public static Item armuremagique22;
	public static Item armuremagique23;
	public static Item armuremagique24;
	public static Item armuremagique25;
	public static Item armuremagique26;
	public static Item armuremagique27;
	public static Item armuremagique28;
	public static Item armuremagique29;
	public static Item armuremagique30;
	public static Item casqueleger1;
	public static Item casqueleger2;
	public static Item casqueleger3;
	public static Item casqueleger4;
	public static Item casqueleger5;
	public static Item casqueleger6;
	public static Item casqueleger7;
	public static Item casqueleger8;
	public static Item casqueleger9;
	public static Item casqueleger10;
	public static Item casqueleger11;
	public static Item casqueleger12;
	public static Item casqueleger13;
	public static Item casqueleger14;
	public static Item casqueleger15;
	public static Item casqueleger16;
	public static Item casqueleger17;
	public static Item casqueleger18;
	public static Item casqueleger19;
	public static Item casqueleger20;
	public static Item casqueleger21;
	public static Item casqueleger22;
	public static Item casqueleger23;
	public static Item casqueleger24;
	public static Item casqueleger25;
	public static Item casqueleger26;
	public static Item casqueleger27;
	public static Item casqueleger28;
	public static Item casqueleger29;
	public static Item casqueleger30;
	public static Item casquelourd1;
	public static Item casquelourd2;
	public static Item casquelourd3;
	public static Item casquelourd4;
	public static Item casquelourd5;
	public static Item casquelourd6;
	public static Item casquelourd7;
	public static Item casquelourd8;
	public static Item casquelourd9;
	public static Item casquelourd10;
	public static Item casquelourd11;
	public static Item casquelourd12;
	public static Item casquelourd13;
	public static Item casquelourd14;
	public static Item casquelourd15;
	public static Item casquelourd16;
	public static Item casquelourd17;
	public static Item casquelourd18;
	public static Item casquelourd19;
	public static Item casquelourd20;
	public static Item casquelourd21;
	public static Item casquelourd22;
	public static Item casquelourd23;
	public static Item casquelourd24;
	public static Item casquelourd25;
	public static Item casquelourd26;
	public static Item casquelourd27;
	public static Item casquelourd28;
	public static Item casquelourd29;
	public static Item casquelourd30;
	public static Item casquemagique1;
	public static Item casquemagique2;
	public static Item casquemagique3;
	public static Item casquemagique4;
	public static Item casquemagique5;
	public static Item casquemagique6;
	public static Item casquemagique7;
	public static Item casquemagique8;
	public static Item casquemagique9;
	public static Item casquemagique10;
	public static Item casquemagique11;
	public static Item casquemagique12;
	public static Item casquemagique13;
	public static Item casquemagique14;
	public static Item casquemagique15;
	public static Item casquemagique16;
	public static Item casquemagique17;
	public static Item casquemagique18;
	public static Item casquemagique19;
	public static Item casquemagique20;
	public static Item casquemagique21;
	public static Item casquemagique22;
	public static Item casquemagique23;
	public static Item casquemagique24;
	public static Item casquemagique25;
	public static Item casquemagique26;
	public static Item casquemagique27;
	public static Item casquemagique28;
	public static Item casquemagique29;
	public static Item casquemagique30;
	public static Item casquemagique31;
	
	public static void init() {
		armorbase = new ArmorMod("armorbase", armor, 1, EntityEquipmentSlot.CHEST);
		Ac_Necklace01 = new ArmorMod("Ac_Necklace01", armor, 2, EntityEquipmentSlot.LEGS);
		Ac_Necklace02 = new ArmorMod("Ac_Necklace02", armor, 2, EntityEquipmentSlot.LEGS);
		Ac_Necklace03 = new ArmorMod("Ac_Necklace03", armor, 2, EntityEquipmentSlot.LEGS);
		Ac_Necklace04 = new ArmorMod("Ac_Necklace04", armor, 2, EntityEquipmentSlot.LEGS);
		Ac_Ring04 = new ArmorMod("Ac_Ring04", armor, 3, EntityEquipmentSlot.FEET);
		icon_15 = new ArmorMod("icon_15", armor, 3, EntityEquipmentSlot.FEET); 
		icon_16 = new ArmorMod("icon_16", armor, 3, EntityEquipmentSlot.FEET);
		icon_17 = new ArmorMod("icon_17", armor, 3, EntityEquipmentSlot.FEET);
		icon_18 = new ArmorMod("icon_18", armor, 3, EntityEquipmentSlot.FEET);
		icon_19 = new ArmorMod("icon_19", armor, 3, EntityEquipmentSlot.FEET);
		icon_20 = new ArmorMod("icon_20", armor, 3, EntityEquipmentSlot.FEET);
		icon_21 = new ArmorMod("icon_21", armor, 3, EntityEquipmentSlot.FEET);
		icon_22 = new ArmorMod("icon_22", armor, 3, EntityEquipmentSlot.FEET);
		icon_23 = new ArmorMod("icon_23", armor, 3, EntityEquipmentSlot.LEGS);
		icon_24 = new ArmorMod("icon_24", armor, 3, EntityEquipmentSlot.LEGS);
		icon_25 = new ArmorMod("icon_25", armor, 3, EntityEquipmentSlot.LEGS);
		icon_27 = new ArmorMod("icon_27", armor, 3, EntityEquipmentSlot.FEET);
		icon_28 = new ArmorMod("icon_28", armor, 3, EntityEquipmentSlot.LEGS);
		necklace_01a = new ArmorMod("necklace_01a", armor, 2, EntityEquipmentSlot.LEGS);
		necklace_01b = new ArmorMod("necklace_01b", armor, 2, EntityEquipmentSlot.LEGS);
		necklace_01c = new ArmorMod("necklace_01c", armor, 2, EntityEquipmentSlot.LEGS);
	    necklace_01d = new ArmorMod("necklace_01d", armor, 2, EntityEquipmentSlot.LEGS);
	    master_jewel = new ArmorMod("master_jewel", armor, 2, EntityEquipmentSlot.LEGS);
	    mithril_jewel = new ArmorMod("mithril_jewel", armor, 2, EntityEquipmentSlot.LEGS);
		trilogy_jewel = new ArmorMod("trilogy_jewel", armor, 2, EntityEquipmentSlot.LEGS);
		adamant_jewel = new ArmorMod("adamant_jewel", armor, 2, EntityEquipmentSlot.LEGS);
		amulette1 = new ArmorMod("amulette1", armor, 2, EntityEquipmentSlot.LEGS);
		amulette2 = new ArmorMod("amulette2", armor, 2, EntityEquipmentSlot.LEGS);
		amulette3 = new ArmorMod("amulette3", armor, 2, EntityEquipmentSlot.LEGS);
		amulette4 = new ArmorMod("amulette4", armor, 2, EntityEquipmentSlot.LEGS);
		amulette5 = new ArmorMod("amulette5", armor, 2, EntityEquipmentSlot.LEGS);
		amulette6 = new ArmorMod("amulette6", armor, 2, EntityEquipmentSlot.LEGS);
		amulette7 = new ArmorMod("amulette7", armor, 2, EntityEquipmentSlot.LEGS);
		amulette8 = new ArmorMod("amulette8", armor, 2, EntityEquipmentSlot.LEGS);
		amulette9 = new ArmorMod("amulette9", armor, 2, EntityEquipmentSlot.LEGS);
		amulette10 = new ArmorMod("amulette10", armor, 2, EntityEquipmentSlot.LEGS);
		amulette11 = new ArmorMod("amulette11", armor, 2, EntityEquipmentSlot.LEGS);
		amulette12 = new ArmorMod("amulette12", armor, 2, EntityEquipmentSlot.LEGS);
		amulette13 = new ArmorMod("amulette13", armor, 2, EntityEquipmentSlot.LEGS);
		amulette14 = new ArmorMod("amulette14", armor, 2, EntityEquipmentSlot.LEGS);
		amulette15 = new ArmorMod("amulette15", armor, 2, EntityEquipmentSlot.LEGS);
		amulette16 = new ArmorMod("amulette16", armor, 2, EntityEquipmentSlot.LEGS);
		amulette17 = new ArmorMod("amulette17", armor, 2, EntityEquipmentSlot.LEGS);
		amulette18 = new ArmorMod("amulette18", armor, 2, EntityEquipmentSlot.LEGS);
		amulette19 = new ArmorMod("amulette19", armor, 2, EntityEquipmentSlot.LEGS);
		amulette20 = new ArmorMod("amulette20", armor, 2, EntityEquipmentSlot.LEGS);
		amulette21 = new ArmorMod("amulette21", armor, 2, EntityEquipmentSlot.LEGS);
		amulette22 = new ArmorMod("amulette22", armor, 2, EntityEquipmentSlot.LEGS);
		amulette23 = new ArmorMod("amulette23", armor, 2, EntityEquipmentSlot.LEGS);
		amulette24 = new ArmorMod("amulette24", armor, 2, EntityEquipmentSlot.LEGS);
		amulette25 = new ArmorMod("amulette25", armor, 2, EntityEquipmentSlot.LEGS);
		amulette26 = new ArmorMod("amulette26", armor, 2, EntityEquipmentSlot.LEGS);
		amulette27 = new ArmorMod("amulette27", armor, 2, EntityEquipmentSlot.LEGS);
		amulette28 = new ArmorMod("amulette28", armor, 2, EntityEquipmentSlot.LEGS);
		amulette29 = new ArmorMod("amulette29", armor, 2, EntityEquipmentSlot.LEGS);
		amulette30 = new ArmorMod("amulette30", armor, 2, EntityEquipmentSlot.LEGS);
		amulette31 = new ArmorMod("amulette31", armor, 2, EntityEquipmentSlot.LEGS);
		amulette32 = new ArmorMod("amulette32", armor, 2, EntityEquipmentSlot.LEGS);
		amulette33 = new ArmorMod("amulette33", armor, 2, EntityEquipmentSlot.LEGS);
		amulette34 = new ArmorMod("amulette34", armor, 2, EntityEquipmentSlot.LEGS);
		amulette35 = new ArmorMod("amulette35", armor, 2, EntityEquipmentSlot.LEGS);
		amulette36 = new ArmorMod("amulette36", armor, 2, EntityEquipmentSlot.LEGS);
		amulette37 = new ArmorMod("amulette37", armor, 2, EntityEquipmentSlot.LEGS);
		amulette38 = new ArmorMod("amulette38", armor, 2, EntityEquipmentSlot.LEGS);
		amulette39 = new ArmorMod("amulette39", armor, 2, EntityEquipmentSlot.LEGS);
		amulette40 = new ArmorMod("amulette40", armor, 2, EntityEquipmentSlot.LEGS);
		anneau1 = new ArmorMod("anneau1", armor, 3, EntityEquipmentSlot.FEET);
		anneau2 = new ArmorMod("anneau2", armor, 3, EntityEquipmentSlot.FEET);
		anneau3 = new ArmorMod("anneau3", armor, 3, EntityEquipmentSlot.FEET);
		anneau4 = new ArmorMod("anneau4", armor, 3, EntityEquipmentSlot.FEET);
		anneau5 = new ArmorMod("anneau5", armor, 3, EntityEquipmentSlot.FEET);
		anneau6 = new ArmorMod("anneau6", armor, 3, EntityEquipmentSlot.FEET);
		anneau7 = new ArmorMod("anneau7", armor, 3, EntityEquipmentSlot.FEET);
		anneau8 = new ArmorMod("anneau8", armor, 3, EntityEquipmentSlot.FEET);
		anneau9 = new ArmorMod("anneau9", armor, 3, EntityEquipmentSlot.FEET);
		anneau10 = new ArmorMod("anneau10", armor, 3, EntityEquipmentSlot.FEET);
		anneau11 = new ArmorMod("anneau11", armor, 3, EntityEquipmentSlot.FEET);
		anneau12 = new ArmorMod("anneau12", armor, 3, EntityEquipmentSlot.FEET);
		anneau13 = new ArmorMod("anneau13", armor, 3, EntityEquipmentSlot.FEET);
		anneau14 = new ArmorMod("anneau14", armor, 3, EntityEquipmentSlot.FEET);
		anneau15 = new ArmorMod("anneau15", armor, 3, EntityEquipmentSlot.FEET);
		anneau16 = new ArmorMod("anneau16", armor, 3, EntityEquipmentSlot.FEET);
		anneau17 = new ArmorMod("anneau17", armor, 3, EntityEquipmentSlot.FEET);
		anneau18 = new ArmorMod("anneau18", armor, 3, EntityEquipmentSlot.FEET);
		anneau19 = new ArmorMod("anneau19", armor, 3, EntityEquipmentSlot.FEET);
		anneau20 = new ArmorMod("anneau20", armor, 3, EntityEquipmentSlot.FEET);
		anneau21 = new ArmorMod("anneau21", armor, 3, EntityEquipmentSlot.FEET);
		anneau22 = new ArmorMod("anneau22", armor, 3, EntityEquipmentSlot.FEET);
		anneau23 = new ArmorMod("anneau23", armor, 3, EntityEquipmentSlot.FEET);
		anneau24 = new ArmorMod("anneau24", armor, 3, EntityEquipmentSlot.FEET);
		anneau25 = new ArmorMod("anneau25", armor, 3, EntityEquipmentSlot.FEET);
		anneau26 = new ArmorMod("anneau26", armor, 3, EntityEquipmentSlot.FEET);
		anneau27 = new ArmorMod("anneau27", armor, 3, EntityEquipmentSlot.FEET);
		anneau28 = new ArmorMod("anneau28", armor, 3, EntityEquipmentSlot.FEET);
		anneau29 = new ArmorMod("anneau29", armor, 3, EntityEquipmentSlot.FEET);
		anneau30 = new ArmorMod("anneau30", armor, 3, EntityEquipmentSlot.FEET);
		anneau31 = new ArmorMod("anneau31", armor, 3, EntityEquipmentSlot.FEET);
		anneau32 = new ArmorMod("anneau32", armor, 3, EntityEquipmentSlot.FEET);
		anneau33 = new ArmorMod("anneau33", armor, 3, EntityEquipmentSlot.FEET);
		anneau34 = new ArmorMod("anneau34", armor, 3, EntityEquipmentSlot.FEET);
		anneau35 = new ArmorMod("anneau35", armor, 3, EntityEquipmentSlot.FEET);
		anneau36 = new ArmorMod("anneau36", armor, 3, EntityEquipmentSlot.FEET);
		anneau37 = new ArmorMod("anneau37", armor, 3, EntityEquipmentSlot.FEET);
		anneau38 = new ArmorMod("anneau38", armor, 3, EntityEquipmentSlot.FEET);
		anneau39 = new ArmorMod("anneau39", armor, 3, EntityEquipmentSlot.FEET);
		armurelegere1 = new ArmorMod("armurelegere1", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere2 = new ArmorMod("armurelegere2", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere3 = new ArmorMod("armurelegere3", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere4 = new ArmorMod("armurelegere4", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere5 = new ArmorMod("armurelegere5", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere6 = new ArmorMod("armurelegere6", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere7 = new ArmorMod("armurelegere7", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere8 = new ArmorMod("armurelegere8", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere9 = new ArmorMod("armurelegere9", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere10 = new ArmorMod("armurelegere10", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere11 = new ArmorMod("armurelegere11", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere12 = new ArmorMod("armurelegere12", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere13 = new ArmorMod("armurelegere13", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere14 = new ArmorMod("armurelegere14", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere15 = new ArmorMod("armurelegere15", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere16 = new ArmorMod("armurelegere16", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere17 = new ArmorMod("armurelegere17", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere18 = new ArmorMod("armurelegere18", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere19 = new ArmorMod("armurelegere19", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere20 = new ArmorMod("armurelegere20", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere21 = new ArmorMod("armurelegere21", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere22 = new ArmorMod("armurelegere22", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere23 = new ArmorMod("armurelegere23", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere24 = new ArmorMod("armurelegere24", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere25 = new ArmorMod("armurelegere25", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere26 = new ArmorMod("armurelegere26", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere27 = new ArmorMod("armurelegere27", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere28 = new ArmorMod("armurelegere28", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere29 = new ArmorMod("armurelegere29", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere30 = new ArmorMod("armurelegere30", armor, 1, EntityEquipmentSlot.CHEST);
		armurelegere31 = new ArmorMod("armurelegere31", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde1 = new ArmorMod("armurelourde1", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde2 = new ArmorMod("armurelourde2", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde3 = new ArmorMod("armurelourde3", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde4 = new ArmorMod("armurelourde4", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde5 = new ArmorMod("armurelourde5", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde6 = new ArmorMod("armurelourde6", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde7 = new ArmorMod("armurelourde7", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde8 = new ArmorMod("armurelourde8", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde9 = new ArmorMod("armurelourde9", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde10 = new ArmorMod("armurelourde10", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde11 = new ArmorMod("armurelourde11", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde12 = new ArmorMod("armurelourde12", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde13 = new ArmorMod("armurelourde13", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde14 = new ArmorMod("armurelourde14", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde15 = new ArmorMod("armurelourde15", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde16 = new ArmorMod("armurelourde16", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde17 = new ArmorMod("armurelourde17", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde18 = new ArmorMod("armurelourde18", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde19 = new ArmorMod("armurelourde19", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde20 = new ArmorMod("armurelourde20", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde21 = new ArmorMod("armurelourde21", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde22 = new ArmorMod("armurelourde22", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde23 = new ArmorMod("armurelourde23", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde24 = new ArmorMod("armurelourde24", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde25 = new ArmorMod("armurelourde25", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde26 = new ArmorMod("armurelourde26", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde27 = new ArmorMod("armurelourde27", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde28 = new ArmorMod("armurelourde28", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde29 = new ArmorMod("armurelourde29", armor, 1, EntityEquipmentSlot.CHEST);
		armurelourde30 = new ArmorMod("armurelourde30", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique1 = new ArmorMod("armuremagique1", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique2 = new ArmorMod("armuremagique2", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique3 = new ArmorMod("armuremagique3", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique4 = new ArmorMod("armuremagique4", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique5 = new ArmorMod("armuremagique5", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique6 = new ArmorMod("armuremagique6", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique7 = new ArmorMod("armuremagique7", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique8 = new ArmorMod("armuremagique8", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique9 = new ArmorMod("armuremagique9", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique10 = new ArmorMod("armuremagique10", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique11 = new ArmorMod("armuremagique11", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique12 = new ArmorMod("armuremagique12", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique13 = new ArmorMod("armuremagique13", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique14 = new ArmorMod("armuremagique14", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique15 = new ArmorMod("armuremagique15", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique16 = new ArmorMod("armuremagique16", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique17 = new ArmorMod("armuremagique17", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique18 = new ArmorMod("armuremagique18", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique19 = new ArmorMod("armuremagique19", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique20 = new ArmorMod("armuremagique20", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique21 = new ArmorMod("armuremagique21", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique22 = new ArmorMod("armuremagique22", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique23 = new ArmorMod("armuremagique23", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique24 = new ArmorMod("armuremagique24", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique25 = new ArmorMod("armuremagique25", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique26 = new ArmorMod("armuremagique26", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique27 = new ArmorMod("armuremagique27", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique28 = new ArmorMod("armuremagique28", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique29 = new ArmorMod("armuremagique29", armor, 1, EntityEquipmentSlot.CHEST);
		armuremagique30 = new ArmorMod("armuremagique30", armor, 1, EntityEquipmentSlot.CHEST);
		casqueleger1 = new ArmorMod("casqueleger1", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger2 = new ArmorMod("casqueleger2", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger3 = new ArmorMod("casqueleger3", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger4 = new ArmorMod("casqueleger4", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger5 = new ArmorMod("casqueleger5", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger6 = new ArmorMod("casqueleger6", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger7 = new ArmorMod("casqueleger7", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger8 = new ArmorMod("casqueleger8", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger9 = new ArmorMod("casqueleger9", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger10 = new ArmorMod("casqueleger10", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger11 = new ArmorMod("casqueleger11", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger12 = new ArmorMod("casqueleger12", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger13 = new ArmorMod("casqueleger13", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger14 = new ArmorMod("casqueleger14", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger15 = new ArmorMod("casqueleger15", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger16 = new ArmorMod("casqueleger16", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger17 = new ArmorMod("casqueleger17", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger18 = new ArmorMod("casqueleger18", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger19 = new ArmorMod("casqueleger19", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger20 = new ArmorMod("casqueleger20", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger21 = new ArmorMod("casqueleger21", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger22 = new ArmorMod("casqueleger22", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger23 = new ArmorMod("casqueleger23", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger24 = new ArmorMod("casqueleger24", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger25 = new ArmorMod("casqueleger25", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger26 = new ArmorMod("casqueleger26", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger27 = new ArmorMod("casqueleger27", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger28 = new ArmorMod("casqueleger28", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger29 = new ArmorMod("casqueleger29", armor, 0, EntityEquipmentSlot.HEAD);
		casqueleger30 = new ArmorMod("casqueleger30", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd1 = new ArmorMod("casquelourd1", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd2 = new ArmorMod("casquelourd2", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd3 = new ArmorMod("casquelourd3", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd4 = new ArmorMod("casquelourd4", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd5 = new ArmorMod("casquelourd5", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd6 = new ArmorMod("casquelourd6", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd7 = new ArmorMod("casquelourd7", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd8 = new ArmorMod("casquelourd8", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd9 = new ArmorMod("casquelourd9", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd10 = new ArmorMod("casquelourd10", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd11 = new ArmorMod("casquelourd11", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd12 = new ArmorMod("casquelourd12", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd13 = new ArmorMod("casquelourd13", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd14 = new ArmorMod("casquelourd14", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd15 = new ArmorMod("casquelourd15", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd16 = new ArmorMod("casquelourd16", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd17 = new ArmorMod("casquelourd17", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd18 = new ArmorMod("casquelourd18", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd19 = new ArmorMod("casquelourd19", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd20 = new ArmorMod("casquelourd20", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd21 = new ArmorMod("casquelourd21", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd22 = new ArmorMod("casquelourd22", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd23 = new ArmorMod("casquelourd23", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd24 = new ArmorMod("casquelourd24", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd25 = new ArmorMod("casquelourd25", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd26 = new ArmorMod("casquelourd26", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd27 = new ArmorMod("casquelourd27", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd28 = new ArmorMod("casquelourd28", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd29 = new ArmorMod("casquelourd29", armor, 0, EntityEquipmentSlot.HEAD);
		casquelourd30 = new ArmorMod("casquelourd30", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique1 = new ArmorMod("casquemagique1", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique2 = new ArmorMod("casquemagique2", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique3 = new ArmorMod("casquemagique3", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique4 = new ArmorMod("casquemagique4", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique5 = new ArmorMod("casquemagique5", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique6 = new ArmorMod("casquemagique6", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique7 = new ArmorMod("casquemagique7", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique8 = new ArmorMod("casquemagique8", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique9 = new ArmorMod("casquemagique9", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique10 = new ArmorMod("casquemagique10", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique11 = new ArmorMod("casquemagique11", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique12 = new ArmorMod("casquemagique12", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique13 = new ArmorMod("casquemagique13", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique14 = new ArmorMod("casquemagique14", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique15 = new ArmorMod("casquemagique15", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique16 = new ArmorMod("casquemagique16", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique17 = new ArmorMod("casquemagique17", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique18 = new ArmorMod("casquemagique18", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique19 = new ArmorMod("casquemagique19", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique20 = new ArmorMod("casquemagique20", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique21 = new ArmorMod("casquemagique21", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique22 = new ArmorMod("casquemagique22", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique23 = new ArmorMod("casquemagique23", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique24 = new ArmorMod("casquemagique24", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique25 = new ArmorMod("casquemagique25", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique26 = new ArmorMod("casquemagique26", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique27 = new ArmorMod("casquemagique27", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique28 = new ArmorMod("casquemagique28", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique29 = new ArmorMod("casquemagique29", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique30 = new ArmorMod("casquemagique30", armor, 0, EntityEquipmentSlot.HEAD);
		casquemagique31 = new ArmorMod("casquemagique31", armor, 0, EntityEquipmentSlot.HEAD);


	}
	
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(armorbase,
		Ac_Necklace01,
		Ac_Necklace02,
		Ac_Necklace03,
		Ac_Necklace04,
		Ac_Ring04,
		icon_15,
		icon_16,
		icon_17,
		icon_18,
		icon_19,
		icon_20,
		icon_21,
		icon_22,
		icon_23,
		icon_24,
		icon_25,
		icon_27,
		necklace_01a,
		necklace_01b,
		necklace_01c,
		necklace_01d,
		 icon_28,
		 master_jewel,
		 mithril_jewel,
		 trilogy_jewel,
		 adamant_jewel, amulette1, amulette2, amulette3, amulette4, amulette5, amulette6, amulette7, amulette8, amulette9, amulette10, amulette11, amulette12, amulette13, amulette14, amulette15, amulette16, amulette17, amulette18, amulette19, amulette20, amulette21, amulette22, amulette23, amulette24, amulette25, amulette26, amulette27, amulette28, amulette29, amulette30, amulette31, amulette32, amulette33, amulette34, amulette35, amulette36, amulette37, amulette38, amulette39, amulette40,
		 anneau1, anneau2, anneau3, anneau4, anneau5, anneau6, anneau7, anneau8, anneau9, anneau10, anneau11, anneau12, anneau13, anneau14, anneau15, anneau16, anneau17, anneau18, anneau19, anneau20, anneau21, anneau22, anneau23, anneau24, anneau25, anneau26, anneau27, anneau28, anneau29, anneau30, anneau31, anneau32, anneau33, anneau34, anneau35, anneau36, anneau37, anneau38, anneau39,
		armurelegere1, armurelegere2, armurelegere3, armurelegere4, armurelegere5, armurelegere6, armurelegere7, armurelegere8, armurelegere9, armurelegere10, armurelegere11, armurelegere12, armurelegere13, armurelegere14, armurelegere15, armurelegere16, armurelegere17, armurelegere18, armurelegere19, armurelegere20, armurelegere21, armurelegere22, armurelegere23, armurelegere24, armurelegere25, armurelegere26, armurelegere27, armurelegere28, armurelegere29, armurelegere30, armurelegere31, armurelourde1, armurelourde2, armurelourde3, armurelourde4, armurelourde5, armurelourde6, armurelourde7, armurelourde8, armurelourde9, armurelourde10, armurelourde11, armurelourde12, armurelourde13, armurelourde14, armurelourde15, armurelourde16, armurelourde17, armurelourde18, armurelourde19, armurelourde20, armurelourde21, armurelourde22, armurelourde23, armurelourde24, armurelourde25, armurelourde26, armurelourde27, armurelourde28, armurelourde29, armurelourde30, armuremagique1, armuremagique2, armuremagique3, armuremagique4, armuremagique5, armuremagique6, armuremagique7, armuremagique8, armuremagique9, armuremagique10, armuremagique11, armuremagique12, armuremagique13, armuremagique14, armuremagique15, armuremagique16, armuremagique17, armuremagique18, armuremagique19, armuremagique20, armuremagique21, armuremagique22, armuremagique23, armuremagique24, armuremagique25, armuremagique26, armuremagique27, armuremagique28, armuremagique29, armuremagique30
		, casqueleger1, casqueleger2, casqueleger3, casqueleger4, casqueleger5, casqueleger6, casqueleger7, casqueleger8, casqueleger9, casqueleger10, casqueleger11, casqueleger12, casqueleger13, casqueleger14, casqueleger15, casqueleger16, casqueleger17, casqueleger18, casqueleger19, casqueleger20, casqueleger21, casqueleger22, casqueleger23, casqueleger24, casqueleger25, casqueleger26, casqueleger27, casqueleger28, casqueleger29, casqueleger30, casquelourd1, casquelourd2, casquelourd3, casquelourd4, casquelourd5, casquelourd6, casquelourd7, casquelourd8, casquelourd9, casquelourd10, casquelourd11, casquelourd12, casquelourd13, casquelourd14, casquelourd15, casquelourd16, casquelourd17, casquelourd18, casquelourd19, casquelourd20, casquelourd21, casquelourd22, casquelourd23, casquelourd24, casquelourd25, casquelourd26, casquelourd27, casquelourd28, casquelourd29, casquelourd30, casquemagique1, casquemagique2, casquemagique3, casquemagique4, casquemagique5, casquemagique6, casquemagique7, casquemagique8, casquemagique9, casquemagique10, casquemagique11, casquemagique12, casquemagique13, casquemagique14, casquemagique15, casquemagique16, casquemagique17, casquemagique18, casquemagique19, casquemagique20, casquemagique21, casquemagique22, casquemagique23, casquemagique24, casquemagique25, casquemagique26, casquemagique27, casquemagique28, casquemagique29, casquemagique30, casquemagique31);
	}
	
	@SubscribeEvent
	public static void registerRenders(ModelRegistryEvent event)
	{
		registerRender(armorbase);
		registerRender(Ac_Necklace01);
		registerRender(Ac_Necklace02);
		registerRender(Ac_Necklace03);
		registerRender(Ac_Necklace04);
		registerRender(Ac_Ring04);
		registerRender(icon_15);
		registerRender(icon_16);
		registerRender(icon_17);
		registerRender(icon_18);
		registerRender(icon_19);
		registerRender(icon_20);
		registerRender(icon_21);
		registerRender(icon_22);
		registerRender(icon_23);
		registerRender(icon_24);
		registerRender(icon_25);
		registerRender(icon_27);
		registerRender(necklace_01a);
		registerRender(necklace_01b);
		registerRender(necklace_01c);
		registerRender(necklace_01d);
		registerRender(adamant_jewel);
		registerRender(icon_28);
		registerRender(master_jewel);
		registerRender(mithril_jewel);
		registerRender(trilogy_jewel);
		registerRender(amulette1);
		registerRender(amulette2);
		registerRender(amulette3);
		registerRender(amulette4);
		registerRender(amulette5);
		registerRender(amulette6);
		registerRender(amulette7);
		registerRender(amulette8);
		registerRender(amulette9);
		registerRender(amulette10);
		registerRender(amulette11);
		registerRender(amulette12);
		registerRender(amulette13);
		registerRender(amulette14);
		registerRender(amulette15);
		registerRender(amulette16);
		registerRender(amulette17);
		registerRender(amulette18);
		registerRender(amulette19);
		registerRender(amulette20);
		registerRender(amulette21);
		registerRender(amulette22);
		registerRender(amulette23);
		registerRender(amulette24);
		registerRender(amulette25);
		registerRender(amulette26);
		registerRender(amulette27);
		registerRender(amulette28);
		registerRender(amulette29);
		registerRender(amulette30);
		registerRender(amulette31);
		registerRender(amulette32);
		registerRender(amulette33);
		registerRender(amulette34);
		registerRender(amulette35);
		registerRender(amulette36);
		registerRender(amulette37);
		registerRender(amulette38);
		registerRender(amulette39);
		registerRender(amulette40);
		registerRender(anneau1);
		registerRender(anneau2);
		registerRender(anneau3);
		registerRender(anneau4);
		registerRender(anneau5);
		registerRender(anneau6);
		registerRender(anneau7);
		registerRender(anneau8);
		registerRender(anneau9);
		registerRender(anneau10);
		registerRender(anneau11);
		registerRender(anneau12);
		registerRender(anneau13);
		registerRender(anneau14);
		registerRender(anneau15);
		registerRender(anneau16);
		registerRender(anneau17);
		registerRender(anneau18);
		registerRender(anneau19);
		registerRender(anneau20);
		registerRender(anneau21);
		registerRender(anneau22);
		registerRender(anneau23);
		registerRender(anneau24);
		registerRender(anneau25);
		registerRender(anneau26);
		registerRender(anneau27);
		registerRender(anneau28);
		registerRender(anneau29);
		registerRender(anneau30);
		registerRender(anneau31);
		registerRender(anneau32);
		registerRender(anneau33);
		registerRender(anneau34);
		registerRender(anneau35);
		registerRender(anneau36);
		registerRender(anneau37);
		registerRender(anneau38);
		registerRender(anneau39);
		registerRender(armurelegere1);
		registerRender(armurelegere2);
		registerRender(armurelegere3);
		registerRender(armurelegere4);
		registerRender(armurelegere5);
		registerRender(armurelegere6);
		registerRender(armurelegere7);
		registerRender(armurelegere8);
		registerRender(armurelegere9);
		registerRender(armurelegere10);
		registerRender(armurelegere11);
		registerRender(armurelegere12);
		registerRender(armurelegere13);
		registerRender(armurelegere14);
		registerRender(armurelegere15);
		registerRender(armurelegere16);
		registerRender(armurelegere17);
		registerRender(armurelegere18);
		registerRender(armurelegere19);
		registerRender(armurelegere20);
		registerRender(armurelegere21);
		registerRender(armurelegere22);
		registerRender(armurelegere23);
		registerRender(armurelegere24);
		registerRender(armurelegere25);
		registerRender(armurelegere26);
		registerRender(armurelegere27);
		registerRender(armurelegere28);
		registerRender(armurelegere29);
		registerRender(armurelegere30);
		registerRender(armurelegere31);
		registerRender(armurelourde1);
		registerRender(armurelourde2);
		registerRender(armurelourde3);
		registerRender(armurelourde4);
		registerRender(armurelourde5);
		registerRender(armurelourde6);
		registerRender(armurelourde7);
		registerRender(armurelourde8);
		registerRender(armurelourde9);
		registerRender(armurelourde10);
		registerRender(armurelourde11);
		registerRender(armurelourde12);
		registerRender(armurelourde13);
		registerRender(armurelourde14);
		registerRender(armurelourde15);
		registerRender(armurelourde16);
		registerRender(armurelourde17);
		registerRender(armurelourde18);
		registerRender(armurelourde19);
		registerRender(armurelourde20);
		registerRender(armurelourde21);
		registerRender(armurelourde22);
		registerRender(armurelourde23);
		registerRender(armurelourde24);
		registerRender(armurelourde25);
		registerRender(armurelourde26);
		registerRender(armurelourde27);
		registerRender(armurelourde28);
		registerRender(armurelourde29);
		registerRender(armurelourde30);
		registerRender(armuremagique1);
		registerRender(armuremagique2);
		registerRender(armuremagique3);
		registerRender(armuremagique4);
		registerRender(armuremagique5);
		registerRender(armuremagique6);
		registerRender(armuremagique7);
		registerRender(armuremagique8);
		registerRender(armuremagique9);
		registerRender(armuremagique10);
		registerRender(armuremagique11);
		registerRender(armuremagique12);
		registerRender(armuremagique13);
		registerRender(armuremagique14);
		registerRender(armuremagique15);
		registerRender(armuremagique16);
		registerRender(armuremagique17);
		registerRender(armuremagique18);
		registerRender(armuremagique19);
		registerRender(armuremagique20);
		registerRender(armuremagique21);
		registerRender(armuremagique22);
		registerRender(armuremagique23);
		registerRender(armuremagique24);
		registerRender(armuremagique25);
		registerRender(armuremagique26);
		registerRender(armuremagique27);
		registerRender(armuremagique28);
		registerRender(armuremagique29);
		registerRender(armuremagique30);
		registerRender(casqueleger1);
		registerRender(casqueleger2);
		registerRender(casqueleger3);
		registerRender(casqueleger4);
		registerRender(casqueleger5);
		registerRender(casqueleger6);
		registerRender(casqueleger7);
		registerRender(casqueleger8);
		registerRender(casqueleger9);
		registerRender(casqueleger10);
		registerRender(casqueleger11);
		registerRender(casqueleger12);
		registerRender(casqueleger13);
		registerRender(casqueleger14);
		registerRender(casqueleger15);
		registerRender(casqueleger16);
		registerRender(casqueleger17);
		registerRender(casqueleger18);
		registerRender(casqueleger19);
		registerRender(casqueleger20);
		registerRender(casqueleger21);
		registerRender(casqueleger22);
		registerRender(casqueleger23);
		registerRender(casqueleger24);
		registerRender(casqueleger25);
		registerRender(casqueleger26);
		registerRender(casqueleger27);
		registerRender(casqueleger28);
		registerRender(casqueleger29);
		registerRender(casqueleger30);
		registerRender(casquelourd1);
		registerRender(casquelourd2);
		registerRender(casquelourd3);
		registerRender(casquelourd4);
		registerRender(casquelourd5);
		registerRender(casquelourd6);
		registerRender(casquelourd7);
		registerRender(casquelourd8);
		registerRender(casquelourd9);
		registerRender(casquelourd10);
		registerRender(casquelourd11);
		registerRender(casquelourd12);
		registerRender(casquelourd13);
		registerRender(casquelourd14);
		registerRender(casquelourd15);
		registerRender(casquelourd16);
		registerRender(casquelourd17);
		registerRender(casquelourd18);
		registerRender(casquelourd19);
		registerRender(casquelourd20);
		registerRender(casquelourd21);
		registerRender(casquelourd22);
		registerRender(casquelourd23);
		registerRender(casquelourd24);
		registerRender(casquelourd25);
		registerRender(casquelourd26);
		registerRender(casquelourd27);
		registerRender(casquelourd28);
		registerRender(casquelourd29);
		registerRender(casquelourd30);
		registerRender(casquemagique1);
		registerRender(casquemagique2);
		registerRender(casquemagique3);
		registerRender(casquemagique4);
		registerRender(casquemagique5);
		registerRender(casquemagique6);
		registerRender(casquemagique7);
		registerRender(casquemagique8);
		registerRender(casquemagique9);
		registerRender(casquemagique10);
		registerRender(casquemagique11);
		registerRender(casquemagique12);
		registerRender(casquemagique13);
		registerRender(casquemagique14);
		registerRender(casquemagique15);
		registerRender(casquemagique16);
		registerRender(casquemagique17);
		registerRender(casquemagique18);
		registerRender(casquemagique19);
		registerRender(casquemagique20);
		registerRender(casquemagique21);
		registerRender(casquemagique22);
		registerRender(casquemagique23);
		registerRender(casquemagique24);
		registerRender(casquemagique25);
		registerRender(casquemagique26);
		registerRender(casquemagique27);
		registerRender(casquemagique28);
		registerRender(casquemagique29);
		registerRender(casquemagique30);
		registerRender(casquemagique31);
	}
	
	private static void registerRender(Item item)
	{
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
	}

}
