package fr.wezord.main.init;

import fr.wezord.main.References;
import fr.wezord.main.item.ItemMod;
import fr.wezord.main.item.ShieldMod;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemShield;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = References.MODID)
public class ItemsMod{
	
public static Item sword;
public static Item peau;
public static Item pfee;
public static Item pguerison;
public static Item pmana;
public static Item pneutre;
public static Item porange;
public static Item psimple;
public static Item pvide;
public static Item pvie;
public static Item pvitesse;
public static Item gpeau;
public static Item gpmana;
public static Item gpneutre;
public static Item gpvide;
public static Item gpvie;
public static Item gpvitesse;
public static Item ginsengrootpotion;
public static Item pbenie;
public static Item pdivine;
public static Item pdoree;
public static Item pdraco;
public static Item anciennepotion;
public static Item fbleu;
public static Item fcyan;
public static Item fgris;
public static Item fjaune;
public static Item forange;
public static Item frose;
public static Item frouge;
public static Item fvert;
public static Item fviolet;
public static Item samber;
public static Item sblue;
public static Item sgreen;
public static Item spurple;
public static Item sred;
public static Item swhite;
public static Item egggreen;
public static Item eggyellow;
public static Item pclaire;
public static Item monstersack;
public static Item objet1;
public static Item objet2;
public static Item objet3;
public static Item objet4;
public static Item objet5;
public static Item objet6;
public static Item paquet;
public static Item pierreinvocation;
public static Item sbabyssalnite;
public static Item sbbronze;
public static Item sbconstantan;
public static Item sbcopper;
public static Item sbcoralium;
public static Item sbdarkstone;
public static Item sbdiamond;
public static Item sbdreadium;
public static Item sbelectrum;
public static Item sbelementium;
public static Item sbenderio;
public static Item sbenderiob;
public static Item sbenderiode;
public static Item sbenderium;
public static Item sbethaxium;
public static Item sbfluxra;
public static Item sbfluxrade;
public static Item sbgold;
public static Item sbinvar;
public static Item sbiron;
public static Item sblead;
public static Item sblumium;
public static Item sbmanasteel;
public static Item sbnickel;
public static Item sbobsidian;
public static Item sbplatinum;
public static Item sbrftools;
public static Item sbsignalum;
public static Item sbsilver;
public static Item sbsoulforged;
public static Item sbsteel;
public static Item sbstone;
public static Item sbterrasteel;
public static Item sbtin;
public static Item sbwood;
public static Item Ac_Medal01;
public static Item Ac_Medal02;
public static Item Ac_Medal03;
public static Item Ac_Medal04;
public static Item book_01a;
public static Item book_01b;
public static Item book_01c;
public static Item book_01d;
public static Item book_01e;
public static Item book_01f;
public static Item book_01g;
public static Item book_02a;
public static Item book_02b;
public static Item book_02c;
public static Item book_02d;
public static Item book_02e;
public static Item book_02f;
public static Item book_02g;
public static Item book_03a;
public static Item book_03b;
public static Item book_03c;
public static Item book_03d;
public static Item book_03e;
public static Item book_03f;
public static Item book_03g;
public static Item book_04a;
public static Item book_04b;
public static Item book_04c;
public static Item book_04d;
public static Item book_04e;
public static Item book_04f;
public static Item book_04g;
public static Item book_05a;
public static Item book_05b;
public static Item book_05c;
public static Item book_05d;
public static Item book_05e;
public static Item book_05f;
public static Item book_05g;
public static Item book_06a;
public static Item book_06b;
public static Item book_06c;
public static Item book_06d;
public static Item book_06e;
public static Item book_06f;
public static Item book_06g;
public static Item coin_01d;
public static Item coin_02d;
public static Item coin_03d;
public static Item coin_04d;
public static Item coin_05d;
public static Item crystal_01a;
public static Item crystal_01b;
public static Item crystal_01c;
public static Item crystal_01d;
public static Item crystal_01e;
public static Item crystal_01f;
public static Item crystal_01g;
public static Item crystal_01h;
public static Item crystal_01i;
public static Item crystal_01j;
public static Item E_Bones02;
public static Item E_Bones03;
public static Item E_Gold01;
public static Item E_Gold02;
public static Item E_Metal01;
public static Item E_Metal02;
public static Item gem_01a;
public static Item gem_01b;
public static Item gem_01c;
public static Item gem_01d;
public static Item gem_01e;
public static Item gem_01f;
public static Item gem_01g;
public static Item gem_01h;
public static Item gem_01i;
public static Item gem_01j;
public static Item gift_01a;
public static Item gift_01b;
public static Item I_Agate;
public static Item I_Amethist;
public static Item I_Antidote;
public static Item I_BatWing;
public static Item I_BirdsBeak;
public static Item I_Bone;
public static Item I_Book;
public static Item I_BronzeBar;
public static Item I_BronzeCoin;
public static Item I_C_Mushroom;
public static Item I_C_Nut;
public static Item I_Coal;
public static Item I_Crystal01;
public static Item I_Crystal02;
public static Item I_Crystal03;
public static Item I_Diamond;
public static Item I_Eye;
public static Item I_Fabric;
public static Item I_Fang;
public static Item I_Feather01;
public static Item I_Feather02;
public static Item I_FoxTail;
public static Item I_FrogLeg;
public static Item I_GoldBar;
public static Item I_GoldCoin;
public static Item I_Jade;
public static Item I_Key01;
public static Item I_Key02;
public static Item I_Key03;
public static Item I_Key04;
public static Item I_Key05;
public static Item I_Key06;
public static Item I_Key07;
public static Item I_Leaf;
public static Item I_Map;
public static Item I_Mirror;
public static Item I_Opal;
public static Item I_Rock01;
public static Item I_Rock02;
public static Item I_Rock03;
public static Item I_Rock04;
public static Item I_Rock05;
public static Item I_Rubi;
public static Item I_Saphire;
public static Item I_ScorpionClaw;
public static Item I_Scroll02;
public static Item I_Scroll;
public static Item I_SilverBar;
public static Item I_SilverCoin;
public static Item I_SnailShell;
public static Item I_SolidShell;
public static Item I_Telescope;
public static Item I_Tentacle;
public static Item I_Torch01;
public static Item I_Torch02;
public static Item I_WolfFur;
public static Item icon_26;
public static Item icon_58;
public static Item icon_59;
public static Item icon_60;
public static Item icon_61;
public static Item icon_62;
public static Item icon_66;
public static Item ingot_01a;
public static Item ingot_01b;
public static Item ingot_01c;
public static Item ingot_01d;
public static Item ingot_01e;
public static Item key_01a;
public static Item key_01b;
public static Item key_01c;
public static Item key_01d;
public static Item key_01e;
public static Item key_02a;
public static Item key_02b;
public static Item key_02c;
public static Item key_02d;
public static Item key_02e;
public static Item parchment;
public static Item pearl_01a;
public static Item pearl_01b;
public static Item pearl_01c;
public static Item pearl_01d;
public static Item pearl_01e;
public static Item S_Bow10;
public static Item S_Earth01;
public static Item S_Fire02;
public static Item S_Fire03;
public static Item S_Holy01;
public static Item S_Holy02;
public static Item S_Holy03;
public static Item S_Holy04;
public static Item S_Holy05;
public static Item S_Holy06;
public static Item S_Holy07;
public static Item S_Ice01;
public static Item S_Ice02;
public static Item S_Ice03;
public static Item S_Ice04;
public static Item S_Ice06;
public static Item S_Light01;
public static Item S_Light02;
public static Item S_Light03;
public static Item S_Magic02;
public static Item S_Magic03;
public static Item S_Magic04;
public static Item S_Poison01;
public static Item S_Poison03;
public static Item S_Poison06;
public static Item S_Shadow01;
public static Item S_Shadow02;
public static Item S_Water01;
public static Item S_Water05;
public static Item S_Water07;
public static Item S_Wind03;
public static Item S_Wind04;
public static Item schem_alloy;
public static Item schem_bomb;
public static Item schem_cogwork;
public static Item schem_crossbow;
public static Item schem_forge;
public static Item schem_gears;
public static Item scroll_01a;
public static Item scroll_01b;
public static Item scroll_01c;
public static Item scroll_01d;
public static Item scroll_01e;
public static Item scroll_01f;
public static Item scroll_01g;
public static Item scroll_01h;
public static Item spellbook_01a;
public static Item spellbook_01b;
public static Item spellbook_01c;
public static Item spellbook_01d;
public static Item spellbook_01e;
public static Item spellbook_02a;
public static Item spellbook_02b;
public static Item spellbook_02c;
public static Item spellbook_02d;
public static Item spellbook_02e;
public static Item spellbook_03a;
public static Item spellbook_03b;
public static Item spellbook_03c;
public static Item spellbook_03d;
public static Item spellbook_03e;
public static Item W_Book01;
public static Item W_Book02;
public static Item W_Book03;
public static Item W_Book04;
public static Item W_Book05;
public static Item W_Book06;
public static Item W_Book07;
public static Item runea1;
public static Item runea2;
public static Item runea3;
public static Item runed1;
public static Item runed2;
public static Item runed3;

	
	public static void init()
	{
		sword = new ItemMod("sword");
		peau = new ItemMod("peau");
		pfee = new ItemMod("pfee");
		pguerison = new ItemMod("pguerison");
		pmana = new ItemMod("pmana");
		pneutre = new ItemMod("pneutre");
		porange = new ItemMod("porange");
		psimple = new ItemMod("psimple");
		pvide = new ItemMod("pvide");
		pvie = new ItemMod("pvie");
		pvitesse = new ItemMod("pvitesse");
		ginsengrootpotion = new ItemMod("ginsengrootpotion");
		gpeau = new ItemMod("gpeau");
		gpmana = new ItemMod("gpmana");
		gpneutre = new ItemMod("gpneutre");
		gpvide = new ItemMod("gpvide");
		gpvie = new ItemMod("gpvie");
		gpvitesse = new ItemMod("gpvitesse");
		pbenie = new ItemMod("pbenie");
		pdivine = new ItemMod("pdivine");
		pdoree = new ItemMod("pdoree");
		pdraco = new ItemMod("pdraco");
		anciennepotion = new ItemMod("anciennepotion");
		fbleu = new ItemMod("fbleu");
		fcyan = new ItemMod("fcyan");
		fgris = new ItemMod("fgris");
		fjaune = new ItemMod("fjaune");
		forange = new ItemMod("forange");
		frose = new ItemMod("frose");
		frouge = new ItemMod("frouge");
		fvert = new ItemMod("fvert");
		fviolet = new ItemMod("fviolet");
		samber = new ItemMod("samber");
		sblue = new ItemMod("sblue");
		sgreen = new ItemMod("sgreen");
		spurple = new ItemMod("spurple");
		sred = new ItemMod("sred");
		swhite = new ItemMod("swhite");
		egggreen = new ItemMod("egggreen");
		eggyellow = new ItemMod("eggyellow");
		pclaire = new ItemMod("pclaire");
		monstersack = new ItemMod("monstersack");
		objet1 = new ItemMod("objet1");
		objet2 = new ItemMod("objet2");
		objet3 = new ItemMod("objet3");
		objet4 = new ItemMod("objet4");
		objet5 = new ItemMod("objet5");
		objet6 = new ItemMod("objet6");
		paquet = new ItemMod("paquet");
		pierreinvocation = new ItemMod("pierreinvocation");
		Ac_Medal01 = new ItemMod("Ac_Medal01");
		Ac_Medal02 = new ItemMod("Ac_Medal02");
		Ac_Medal03 = new ItemMod("Ac_Medal03");
		Ac_Medal04 = new ItemMod("Ac_Medal04");
		book_01a = new ItemMod("book_01a");
		book_01b = new ItemMod("book_01b");
		book_01c = new ItemMod("book_01c");
		book_01d = new ItemMod("book_01d");
		book_01e = new ItemMod("book_01e");
		book_01f = new ItemMod("book_01f");
		book_01g = new ItemMod("book_01g");
		book_02a = new ItemMod("book_02a");
		book_02b = new ItemMod("book_02b");
		book_02c = new ItemMod("book_02c");
		book_02d = new ItemMod("book_02d");
		book_02e = new ItemMod("book_02e");
		book_02f = new ItemMod("book_02f");
		book_02g = new ItemMod("book_02g");
		book_03a = new ItemMod("book_03a");
		book_03b = new ItemMod("book_03b");
		book_03c = new ItemMod("book_03c");
		book_03d = new ItemMod("book_03d");
		book_03e = new ItemMod("book_03e");
		book_03f = new ItemMod("book_03f");
		book_03g = new ItemMod("book_03g");
		book_04a = new ItemMod("book_04a");
		book_04b = new ItemMod("book_04b");
		book_04c = new ItemMod("book_04c");
		book_04d = new ItemMod("book_04d");
		book_04e = new ItemMod("book_04e");
		book_04f = new ItemMod("book_04f");
		book_04g = new ItemMod("book_04g");
		book_05a = new ItemMod("book_05a");
		book_05b = new ItemMod("book_05b");
		book_05c = new ItemMod("book_05c");
		book_05d = new ItemMod("book_05d");
		book_05e = new ItemMod("book_05e");
		book_05f = new ItemMod("book_05f");
		book_05g = new ItemMod("book_05g");
		book_06a = new ItemMod("book_06a");
		book_06b = new ItemMod("book_06b");
		book_06c = new ItemMod("book_06c");
		book_06d = new ItemMod("book_06d");
		book_06e = new ItemMod("book_06e");
		book_06f = new ItemMod("book_06f");
		book_06g = new ItemMod("book_06g");
		coin_01d = new ItemMod("coin_01d");
		coin_02d = new ItemMod("coin_02d");
		coin_03d = new ItemMod("coin_03d");
		coin_04d = new ItemMod("coin_04d");
		coin_05d = new ItemMod("coin_05d");
		crystal_01a = new ItemMod("crystal_01a");
		crystal_01b = new ItemMod("crystal_01b");
		crystal_01c = new ItemMod("crystal_01c");
		crystal_01d = new ItemMod("crystal_01d");
		crystal_01e = new ItemMod("crystal_01e");
		crystal_01f = new ItemMod("crystal_01f");
		crystal_01g = new ItemMod("crystal_01g");
		crystal_01h = new ItemMod("crystal_01h");
		crystal_01i = new ItemMod("crystal_01i");
		crystal_01j = new ItemMod("crystal_01j");
		E_Bones02 = new ItemMod("E_Bones02");
		E_Bones03 = new ItemMod("E_Bones03");
		E_Gold01 = new ItemMod("E_Gold01");
		E_Gold02 = new ItemMod("E_Gold02");
		E_Metal01 = new ItemMod("E_Metal01");
		E_Metal02 = new ItemMod("E_Metal02");
		gem_01a = new ItemMod("gem_01a");
		gem_01b = new ItemMod("gem_01b");
		gem_01c = new ItemMod("gem_01c");
		gem_01d = new ItemMod("gem_01d");
		gem_01e = new ItemMod("gem_01e");
		gem_01f = new ItemMod("gem_01f");
		gem_01g = new ItemMod("gem_01g");
		gem_01h = new ItemMod("gem_01h");
		gem_01i = new ItemMod("gem_01i");
		gem_01j = new ItemMod("gem_01j");
		gift_01a = new ItemMod("gift_01a");
		gift_01b = new ItemMod("gift_01b");
		I_Agate = new ItemMod("I_Agate");
		I_Amethist = new ItemMod("I_Amethist");
		I_Antidote = new ItemMod("I_Antidote");
		I_BatWing = new ItemMod("I_BatWing");
		I_BirdsBeak = new ItemMod("I_BirdsBeak");
		I_Bone = new ItemMod("I_Bone");
		I_Book = new ItemMod("I_Book");
		I_BronzeBar = new ItemMod("I_BronzeBar");
		I_BronzeCoin = new ItemMod("I_BronzeCoin");
		I_C_Mushroom = new ItemMod("I_C_Mushroom");
		I_C_Nut = new ItemMod("I_C_Nut");
		I_Coal = new ItemMod("I_Coal");
		I_Crystal01 = new ItemMod("I_Crystal01");
		I_Crystal02 = new ItemMod("I_Crystal02");
		I_Crystal03 = new ItemMod("I_Crystal03");
		I_Diamond = new ItemMod("I_Diamond");
		I_Eye = new ItemMod("I_Eye");
		I_Fabric = new ItemMod("I_Fabric");
		I_Fang = new ItemMod("I_Fang");
		I_Feather01 = new ItemMod("I_Feather01");
		I_Feather02 = new ItemMod("I_Feather02");
		I_FoxTail = new ItemMod("I_FoxTail");
		I_FrogLeg = new ItemMod("I_FrogLeg");
		I_GoldBar = new ItemMod("I_GoldBar");
		I_GoldCoin = new ItemMod("I_GoldCoin");
		I_Jade = new ItemMod("I_Jade");
		I_Key01 = new ItemMod("I_Key01");
		I_Key02 = new ItemMod("I_Key02");
		I_Key03 = new ItemMod("I_Key03");
		I_Key04 = new ItemMod("I_Key04");
		I_Key05 = new ItemMod("I_Key05");
		I_Key06 = new ItemMod("I_Key06");
		I_Key07 = new ItemMod("I_Key07");
		I_Leaf = new ItemMod("I_Leaf");
		I_Map = new ItemMod("I_Map");
		I_Mirror = new ItemMod("I_Mirror");
		I_Opal = new ItemMod("I_Opal");
		I_Rock01 = new ItemMod("I_Rock01");
		I_Rock02 = new ItemMod("I_Rock02");
		I_Rock03 = new ItemMod("I_Rock03");
		I_Rock04 = new ItemMod("I_Rock04");
		I_Rock05 = new ItemMod("I_Rock05");
		I_Rubi = new ItemMod("I_Rubi");
		I_Saphire = new ItemMod("I_Saphire");
		I_ScorpionClaw = new ItemMod("I_ScorpionClaw");
		I_Scroll02 = new ItemMod("I_Scroll02");
		I_Scroll = new ItemMod("I_Scroll");
		I_SilverBar = new ItemMod("I_SilverBar");
		I_SilverCoin = new ItemMod("I_SilverCoin");
		I_SnailShell = new ItemMod("I_SnailShell");
		I_SolidShell = new ItemMod("I_SolidShell");
		I_Telescope = new ItemMod("I_Telescope");
		I_Tentacle = new ItemMod("I_Tentacle");
		I_Torch01 = new ItemMod("I_Torch01");
		I_Torch02 = new ItemMod("I_Torch02");
		I_WolfFur = new ItemMod("I_WolfFur");
		icon_26 = new ItemMod("icon_26");
		icon_58 = new ItemMod("icon_58");
		icon_59 = new ItemMod("icon_59");
		icon_60 = new ItemMod("icon_60");
		icon_61 = new ItemMod("icon_61");
		icon_62 = new ItemMod("icon_62");
		icon_66 = new ItemMod("icon_66");
		ingot_01a = new ItemMod("ingot_01a");
		ingot_01b = new ItemMod("ingot_01b");
		ingot_01c = new ItemMod("ingot_01c");
		ingot_01d = new ItemMod("ingot_01d");
		ingot_01e = new ItemMod("ingot_01e");
		key_01a = new ItemMod("key_01a");
		key_01b = new ItemMod("key_01b");
		key_01c = new ItemMod("key_01c");
		key_01d = new ItemMod("key_01d");
		key_01e = new ItemMod("key_01e");
		key_02a = new ItemMod("key_02a");
		key_02b = new ItemMod("key_02b");
		key_02c = new ItemMod("key_02c");
		key_02d = new ItemMod("key_02d");
		key_02e = new ItemMod("key_02e");
		parchment = new ItemMod("parchment");
		pearl_01a = new ItemMod("pearl_01a");
		pearl_01b = new ItemMod("pearl_01b");
		pearl_01c = new ItemMod("pearl_01c");
		pearl_01d = new ItemMod("pearl_01d");
		pearl_01e = new ItemMod("pearl_01e");
		S_Bow10 = new ItemMod("S_Bow10");
		S_Earth01 = new ItemMod("S_Earth01");
		S_Fire02 = new ItemMod("S_Fire02");
		S_Fire03 = new ItemMod("S_Fire03");
		S_Holy01 = new ItemMod("S_Holy01");
		S_Holy02 = new ItemMod("S_Holy02");
		S_Holy03 = new ItemMod("S_Holy03");
		S_Holy04 = new ItemMod("S_Holy04");
		S_Holy05 = new ItemMod("S_Holy05");
		S_Holy06 = new ItemMod("S_Holy06");
		S_Holy07 = new ItemMod("S_Holy07");
		S_Ice01 = new ItemMod("S_Ice01");
		S_Ice02 = new ItemMod("S_Ice02");
		S_Ice03 = new ItemMod("S_Ice03");
		S_Ice04 = new ItemMod("S_Ice04");
		S_Ice06 = new ItemMod("S_Ice06");
		S_Light01 = new ItemMod("S_Light01");
		S_Light02 = new ItemMod("S_Light02");
		S_Light03 = new ItemMod("S_Light03");
		S_Magic02 = new ItemMod("S_Magic02");
		S_Magic03 = new ItemMod("S_Magic03");
		S_Magic04 = new ItemMod("S_Magic04");
		S_Poison01 = new ItemMod("S_Poison01");
		S_Poison03 = new ItemMod("S_Poison03");
		S_Poison06 = new ItemMod("S_Poison06");
		S_Shadow01 = new ItemMod("S_Shadow01");
		S_Shadow02 = new ItemMod("S_Shadow02");
		S_Water01 = new ItemMod("S_Water01");
		S_Water05 = new ItemMod("S_Water05");
		S_Water07 = new ItemMod("S_Water07");
		S_Wind03 = new ItemMod("S_Wind03");
		S_Wind04 = new ItemMod("S_Wind04");
		schem_alloy = new ItemMod("schem_alloy");
		schem_bomb = new ItemMod("schem_bomb");
		schem_cogwork = new ItemMod("schem_cogwork");
		schem_crossbow = new ItemMod("schem_crossbow");
		schem_forge = new ItemMod("schem_forge");
		schem_gears = new ItemMod("schem_gears");
		scroll_01a = new ItemMod("scroll_01a");
		scroll_01b = new ItemMod("scroll_01b");
		scroll_01c = new ItemMod("scroll_01c");
		scroll_01d = new ItemMod("scroll_01d");
		scroll_01e = new ItemMod("scroll_01e");
		scroll_01f = new ItemMod("scroll_01f");
		scroll_01g = new ItemMod("scroll_01g");
		scroll_01h = new ItemMod("scroll_01h");
		spellbook_01a = new ItemMod("spellbook_01a");
		spellbook_01b = new ItemMod("spellbook_01b");
		spellbook_01c = new ItemMod("spellbook_01c");
		spellbook_01d = new ItemMod("spellbook_01d");
		spellbook_01e = new ItemMod("spellbook_01e");
		spellbook_02a = new ItemMod("spellbook_02a");
		spellbook_02b = new ItemMod("spellbook_02b");
		spellbook_02c = new ItemMod("spellbook_02c");
		spellbook_02d = new ItemMod("spellbook_02d");
		spellbook_02e = new ItemMod("spellbook_02e");
		spellbook_03a = new ItemMod("spellbook_03a");
		spellbook_03b = new ItemMod("spellbook_03b");
		spellbook_03c = new ItemMod("spellbook_03c");
		spellbook_03d = new ItemMod("spellbook_03d");
		spellbook_03e = new ItemMod("spellbook_03e");
		W_Book01 = new ItemMod("W_Book01");
		W_Book02 = new ItemMod("W_Book02");
		W_Book03 = new ItemMod("W_Book03");
		W_Book04 = new ItemMod("W_Book04");
		W_Book05 = new ItemMod("W_Book05");
		W_Book06 = new ItemMod("W_Book06");
		W_Book07 = new ItemMod("W_Book07");
		sbabyssalnite = new ShieldMod("sbabyssalnite");
		sbbronze = new ShieldMod("sbbronze");
		sbconstantan = new ShieldMod("sbconstantan");
		sbcopper = new ShieldMod("sbcopper");
		sbcoralium = new ShieldMod("sbcoralium");
		sbdarkstone = new ShieldMod("sbdarkstone");
		sbdiamond = new ShieldMod("sbdiamond");
		sbdreadium = new ShieldMod("sbdreadium");
		sbelectrum = new ShieldMod("sbelectrum");
		sbelementium = new ShieldMod("sbelementium");
		sbenderio = new ShieldMod("sbenderio");
		sbenderiob = new ShieldMod("sbenderiob");
		sbenderiode = new ShieldMod("sbenderiode");
		sbenderium = new ShieldMod("sbenderium");
		sbethaxium = new ShieldMod("sbethaxium");
		sbfluxra = new ShieldMod("sbfluxra");
		sbfluxrade = new ShieldMod("sbfluxrade");
		sbgold = new ShieldMod("sbgold");
		sbinvar = new ShieldMod("sbinvar");
		sbiron = new ShieldMod("sbiron");
		sblead = new ShieldMod("sblead");
		sblumium = new ShieldMod("sblumium");
		sbmanasteel = new ShieldMod("sbmanasteel");
		sbnickel = new ShieldMod("sbnickel");
		sbobsidian = new ShieldMod("sbobsidian");
		sbplatinum = new ShieldMod("sbplatinum");
		sbrftools = new ShieldMod("sbrftools");
		sbsignalum = new ShieldMod("sbsignalum");
		sbsilver = new ShieldMod("sbsilver");
		sbsoulforged = new ShieldMod("sbsoulforged");
		sbsteel = new ShieldMod("sbsteel");
		sbstone = new ShieldMod("sbstone");
		sbterrasteel = new ShieldMod("sbterrasteel");
		sbtin = new ShieldMod("sbtin");
		sbwood = new ShieldMod("sbwood");
		runea1 = new ItemMod("runea1");
		runea2 = new ItemMod("runea2");
		runea3 = new ItemMod("runea3");
		runed1 = new ItemMod("runed1");
		runed2 = new ItemMod("runed2");
		runed3 = new ItemMod("runed3");
		
	}
	
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().registerAll(sword, peau, pfee, pguerison, pmana, pneutre, porange, psimple, pvide, pvie, pvitesse, ginsengrootpotion
				,gpeau, gpmana, gpneutre ,gpvide , gpvie, gpvitesse, pbenie, pdivine, pdoree, pdraco, anciennepotion, fbleu, fcyan, fgris, fjaune, forange,
				frose, frouge, fvert, fviolet, samber, sblue, sgreen, spurple, sred, swhite,  egggreen, eggyellow,  monstersack, objet1, objet2, objet3, objet4, objet5, objet6, paquet, pierreinvocation,  pclaire, sbabyssalnite, sbbronze, sbconstantan, sbcopper, sbcoralium, sbdarkstone
				, sbdiamond, sbdreadium, sbelectrum, sbelementium, sbenderio, sbenderiob, sbenderiode, sbenderium, sbethaxium, sbfluxra, sbfluxrade, sbgold, sbinvar, sbiron, sblead, sblumium, sbmanasteel, sbnickel, sbobsidian,
				sbplatinum, sbrftools, sbsignalum, sbsilver, sbsoulforged, sbsteel, sbstone, sbterrasteel, sbtin, sbwood, Ac_Medal01, Ac_Medal02, Ac_Medal03, Ac_Medal04, 
				 book_01a, book_01b, book_01c, book_01d, book_01e, book_01f, book_01g, book_02a, book_02b, book_02c, book_02d, book_02e, book_02f, book_02g, book_03a, book_03b, book_03c, book_03d, book_03e, book_03f, book_03g, 
				book_04a, book_04b, book_04c, book_04d, book_04e, book_04f, book_04g, book_05a, book_05b, book_05c, book_05d, book_05e, book_05f, book_05g, book_06a, book_06b, book_06c, book_06d, book_06e, book_06f, book_06g, coin_01d, coin_02d, 
				coin_03d, coin_04d, coin_05d, crystal_01a, crystal_01b, crystal_01c, crystal_01d, crystal_01e, crystal_01f, crystal_01g, crystal_01h, crystal_01i, crystal_01j, E_Bones02, E_Bones03, E_Gold01, E_Gold02, E_Metal01, E_Metal02, gem_01a,
				gem_01b, gem_01c, gem_01d, gem_01e, gem_01f, gem_01g, gem_01h, gem_01i, gem_01j, gift_01a, gift_01b, I_Agate, I_Amethist, I_Antidote, I_BatWing, I_BirdsBeak, I_Bone, I_Book, I_BronzeBar, I_BronzeCoin, I_C_Mushroom, I_C_Nut, I_Coal, I_Crystal01,
				I_Crystal02, I_Crystal03, I_Diamond, I_Eye, I_Fabric, I_Fang, I_Feather01, I_Feather02, I_FoxTail, I_FrogLeg, I_GoldBar, I_GoldCoin, I_Jade, I_Key01, I_Key02, I_Key03, I_Key04, I_Key05, I_Key06, I_Key07, I_Leaf, I_Map, I_Mirror, I_Opal, I_Rock01, I_Rock02, 
				I_Rock03, I_Rock04, I_Rock05, I_Rubi, I_Saphire, I_ScorpionClaw, I_Scroll02, I_Scroll, I_SilverBar, I_SilverCoin, I_SnailShell, I_SolidShell, I_Telescope, I_Tentacle, I_Torch01, I_Torch02, I_WolfFur, 
				 icon_26, icon_58, icon_59, icon_60, icon_61, icon_62, icon_66, ingot_01a, ingot_01b, ingot_01c, ingot_01d, ingot_01e, key_01a, key_01b, key_01c, key_01d, key_01e, key_02a, key_02b, key_02c, key_02d, key_02e, 
				 parchment, pearl_01a, pearl_01b, pearl_01c, pearl_01d, pearl_01e, S_Bow10, S_Earth01, S_Fire02, S_Fire03, S_Holy01, S_Holy02, S_Holy03, S_Holy04, S_Holy05, S_Holy06, S_Holy07,
				S_Ice01, S_Ice02, S_Ice03, S_Ice04, S_Ice06, S_Light01, S_Light02, S_Light03, S_Magic02, S_Magic03, S_Magic04, S_Poison01, S_Poison03, S_Poison06, S_Shadow01, S_Shadow02, S_Water01, S_Water05, S_Water07, S_Wind03, S_Wind04, schem_alloy, schem_bomb, schem_cogwork,
				schem_crossbow, schem_forge, schem_gears, scroll_01a, scroll_01b, scroll_01c, scroll_01d, scroll_01e, scroll_01f, scroll_01g, scroll_01h, spellbook_01a, spellbook_01b, spellbook_01c, spellbook_01d, spellbook_01e, spellbook_02a, spellbook_02b, spellbook_02c, spellbook_02d,
				spellbook_02e, spellbook_03a, spellbook_03b, spellbook_03c, spellbook_03d, spellbook_03e, W_Book01, W_Book02, W_Book03, W_Book04, W_Book05, W_Book06, W_Book07, runea1, runea2, runea3, runed1, runed2, runed3);
	}
	
	@SubscribeEvent
	public static void registerRenders(ModelRegistryEvent event)
	{
		registerRender(sword);
		registerRender(peau);
		registerRender(pfee);
		registerRender(pguerison);
		registerRender(pmana);
		registerRender(pneutre);
		registerRender(pvie);
		registerRender(porange);
		registerRender(psimple);
		registerRender(pvide);
		registerRender(pvitesse);
		registerRender(ginsengrootpotion);
		registerRender(gpeau);
		registerRender(gpmana);
		registerRender(gpneutre);
		registerRender(gpvide);
		registerRender(gpvie);
		registerRender(gpvitesse);
		registerRender(pbenie);
		registerRender(pdivine);
		registerRender(pdoree);
		registerRender(pdraco);
		registerRender(anciennepotion);
		registerRender(fbleu);
		registerRender(fcyan);
		registerRender(fgris);
		registerRender(fjaune);
		registerRender(forange);
		registerRender(frose);
		registerRender(frouge);
		registerRender(fvert);
		registerRender(fviolet);
		registerRender(samber);
		registerRender(sblue);
		registerRender(sgreen);
		registerRender(spurple);
		registerRender(sred);
		registerRender(swhite);
		registerRender(egggreen);
		registerRender(eggyellow);
		registerRender(pclaire);
		registerRender(monstersack);
		registerRender(objet1);
		registerRender(objet2);
		registerRender(objet3);
		registerRender(objet4);
		registerRender(objet5);
		registerRender(objet6);
		registerRender(paquet);
		registerRender(pierreinvocation);
		registerRender(sbabyssalnite);
		registerRender(sbbronze);
		registerRender(sbconstantan);
		registerRender(sbcopper);
		registerRender(sbcoralium);
		registerRender(sbdarkstone);
		registerRender(sbdiamond);
		registerRender(sbdreadium);
		registerRender(sbelectrum);
		registerRender(sbelementium);
		registerRender(sbenderio);
		registerRender(sbenderiob);
		registerRender(sbenderiode);
		registerRender(sbenderium);
		registerRender(sbethaxium);
		registerRender(sbfluxra);
		registerRender(sbfluxrade);
		registerRender(sbgold);
		registerRender(sbinvar);
		registerRender(sbiron);
		registerRender(sblead);
		registerRender(sblumium);
		registerRender(sbmanasteel);
		registerRender(sbnickel);
		registerRender(sbobsidian);
		registerRender(sbplatinum);
		registerRender(sbrftools);
		registerRender(sbsignalum);
		registerRender(sbsilver);
		registerRender(sbsoulforged);
		registerRender(sbsteel);
		registerRender(sbstone);
		registerRender(sbterrasteel);
		registerRender(sbtin);
		registerRender(sbwood);
		registerRender(Ac_Medal01);
		registerRender(Ac_Medal02);
		registerRender(Ac_Medal03);
		registerRender(Ac_Medal04);
		registerRender(book_01a);
		registerRender(book_01b);
		registerRender(book_01c);
		registerRender(book_01d);
		registerRender(book_01e);
		registerRender(book_01f);
		registerRender(book_01g);
		registerRender(book_02a);
		registerRender(book_02b);
		registerRender(book_02c);
		registerRender(book_02d);
		registerRender(book_02e);
		registerRender(book_02f);
		registerRender(book_02g);
		registerRender(book_03a);
		registerRender(book_03b);
		registerRender(book_03c);
		registerRender(book_03d);
		registerRender(book_03e);
		registerRender(book_03f);
		registerRender(book_03g);
		registerRender(book_04a);
		registerRender(book_04b);
		registerRender(book_04c);
		registerRender(book_04d);
		registerRender(book_04e);
		registerRender(book_04f);
		registerRender(book_04g);
		registerRender(book_05a);
		registerRender(book_05b);
		registerRender(book_05c);
		registerRender(book_05d);
		registerRender(book_05e);
		registerRender(book_05f);
		registerRender(book_05g);
		registerRender(book_06a);
		registerRender(book_06b);
		registerRender(book_06c);
		registerRender(book_06d);
		registerRender(book_06e);
		registerRender(book_06f);
		registerRender(book_06g);
		registerRender(coin_01d);
		registerRender(coin_02d);
		registerRender(coin_03d);
		registerRender(coin_04d);
		registerRender(coin_05d);
		registerRender(crystal_01a);
		registerRender(crystal_01b);
		registerRender(crystal_01c);
		registerRender(crystal_01d);
		registerRender(crystal_01e);
		registerRender(crystal_01f);
		registerRender(crystal_01g);
		registerRender(crystal_01h);
		registerRender(crystal_01i);
		registerRender(crystal_01j);
		registerRender(E_Bones02);
		registerRender(E_Bones03);
		registerRender(E_Gold01);
		registerRender(E_Gold02);
		registerRender(E_Metal01);
		registerRender(E_Metal02);
		registerRender(gem_01a);
		registerRender(gem_01b);
		registerRender(gem_01c);
		registerRender(gem_01d);
		registerRender(gem_01e);
		registerRender(gem_01f);
		registerRender(gem_01g);
		registerRender(gem_01h);
		registerRender(gem_01i);
		registerRender(gem_01j);
		registerRender(gift_01a);
		registerRender(gift_01b);
		registerRender(I_Agate);
		registerRender(I_Amethist);
		registerRender(I_Antidote);
		registerRender(I_BatWing);
		registerRender(I_BirdsBeak);
		registerRender(I_Bone);
		registerRender(I_Book);
		registerRender(I_BronzeBar);
		registerRender(I_BronzeCoin);
		registerRender(I_C_Mushroom);
		registerRender(I_C_Nut);
		registerRender(I_Coal);
		registerRender(I_Crystal01);
		registerRender(I_Crystal02);
		registerRender(I_Crystal03);
		registerRender(I_Diamond);
		registerRender(I_Eye);
		registerRender(I_Fabric);
		registerRender(I_Fang);
		registerRender(I_Feather01);
		registerRender(I_Feather02);
		registerRender(I_FoxTail);
		registerRender(I_FrogLeg);
		registerRender(I_GoldBar);
		registerRender(I_GoldCoin);
		registerRender(I_Jade);
		registerRender(I_Key01);
		registerRender(I_Key02);
		registerRender(I_Key03);
		registerRender(I_Key04);
		registerRender(I_Key05);
		registerRender(I_Key06);
		registerRender(I_Key07);
		registerRender(I_Leaf);
		registerRender(I_Map);
		registerRender(I_Mirror);
		registerRender(I_Opal);
		registerRender(I_Rock01);
		registerRender(I_Rock02);
		registerRender(I_Rock03);
		registerRender(I_Rock04);
		registerRender(I_Rock05);
		registerRender(I_Rubi);
		registerRender(I_Saphire);
		registerRender(I_ScorpionClaw);
		registerRender(I_Scroll02);
		registerRender(I_Scroll);
		registerRender(I_SilverBar);
		registerRender(I_SilverCoin);
		registerRender(I_SnailShell);
		registerRender(I_SolidShell);
		registerRender(I_Telescope);
		registerRender(I_Tentacle);
		registerRender(I_Torch01);
		registerRender(I_Torch02);
		registerRender(I_WolfFur);
		registerRender(icon_26);
		registerRender(icon_58);
		registerRender(icon_59);
		registerRender(icon_60);
		registerRender(icon_61);
		registerRender(icon_62);
		registerRender(icon_66);
		registerRender(ingot_01a);
		registerRender(ingot_01b);
		registerRender(ingot_01c);
		registerRender(ingot_01d);
		registerRender(ingot_01e);
		registerRender(key_01a);
		registerRender(key_01b);
		registerRender(key_01c);
		registerRender(key_01d);
		registerRender(key_01e);
		registerRender(key_02a);
		registerRender(key_02b);
		registerRender(key_02c);
		registerRender(key_02d);
		registerRender(key_02e);
		registerRender(parchment);
		registerRender(pearl_01a);
		registerRender(pearl_01b);
		registerRender(pearl_01c);
		registerRender(pearl_01d);
		registerRender(pearl_01e);
		registerRender(S_Bow10);
		registerRender(S_Earth01);
		registerRender(S_Fire02);
		registerRender(S_Fire03);
		registerRender(S_Holy01);
		registerRender(S_Holy02);
		registerRender(S_Holy03);
		registerRender(S_Holy04);
		registerRender(S_Holy05);
		registerRender(S_Holy06);
		registerRender(S_Holy07);
		registerRender(S_Ice01);
		registerRender(S_Ice02);
		registerRender(S_Ice03);
		registerRender(S_Ice04);
		registerRender(S_Ice06);
		registerRender(S_Light01);
		registerRender(S_Light02);
		registerRender(S_Light03);
		registerRender(S_Magic02);
		registerRender(S_Magic03);
		registerRender(S_Magic04);
		registerRender(S_Poison01);
		registerRender(S_Poison03);
		registerRender(S_Poison06);
		registerRender(S_Shadow01);
		registerRender(S_Shadow02);
		registerRender(S_Water01);
		registerRender(S_Water05);
		registerRender(S_Water07);
		registerRender(S_Wind03);
		registerRender(S_Wind04);
		registerRender(schem_alloy);
		registerRender(schem_bomb);
		registerRender(schem_cogwork);
		registerRender(schem_crossbow);
		registerRender(schem_forge);
		registerRender(schem_gears);
		registerRender(scroll_01a);
		registerRender(scroll_01b);
		registerRender(scroll_01c);
		registerRender(scroll_01d);
		registerRender(scroll_01e);
		registerRender(scroll_01f);
		registerRender(scroll_01g);
		registerRender(scroll_01h);
		registerRender(spellbook_01a);
		registerRender(spellbook_01b);
		registerRender(spellbook_01c);
		registerRender(spellbook_01d);
		registerRender(spellbook_01e);
		registerRender(spellbook_02a);
		registerRender(spellbook_02b);
		registerRender(spellbook_02c);
		registerRender(spellbook_02d);
		registerRender(spellbook_02e);
		registerRender(spellbook_03a);
		registerRender(spellbook_03b);
		registerRender(spellbook_03c);
		registerRender(spellbook_03d);
		registerRender(spellbook_03e);
		registerRender(W_Book01);
		registerRender(W_Book02);
		registerRender(W_Book03);
		registerRender(W_Book04);
		registerRender(W_Book05);
		registerRender(W_Book06);
		registerRender(W_Book07);
		registerRender(runea1);
		registerRender(runea2);
		registerRender(runea3);
		registerRender(runed1);
		registerRender(runed2);
		registerRender(runed3);
		
	}
	
	private static void registerRender(Item item)
	{
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
	}
	


}