package fr.wezord.main.util.handler;

import fr.wezord.main.References;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class SoundHandler {
	
	public static SoundEvent arcattaque1;
	public static SoundEvent arcattaque2;
	public static SoundEvent arcattaque3;
	public static SoundEvent arcdouleur1;
	public static SoundEvent arcdouleur2;
	public static SoundEvent arcdouleur3;
	public static SoundEvent arcdouleur4;
	public static SoundEvent arcmort;
	public static SoundEvent arcrespawn1;
	public static SoundEvent arcsaut;
	public static SoundEvent arcspawn1;
	public static SoundEvent arcspawn2;
	public static SoundEvent assattaque1;
	public static SoundEvent assattaque2;
	public static SoundEvent assattaque3;
	public static SoundEvent assdouleur1;
	public static SoundEvent assdouleur2;
	public static SoundEvent assdouleur3;
	public static SoundEvent assdouleur4;
	public static SoundEvent assmort;
	public static SoundEvent assrespawn1;
	public static SoundEvent asssaut;
	public static SoundEvent assspawn1;
	public static SoundEvent assspawn2;
	public static SoundEvent berattaque1;
	public static SoundEvent berattaque2;
	public static SoundEvent berattaque3;
	public static SoundEvent berdouleur1;
	public static SoundEvent berdouleur2;
	public static SoundEvent berdouleur3;
	public static SoundEvent berdouleur4;
	public static SoundEvent bermort;
	public static SoundEvent berrespawn1;
	public static SoundEvent bersaut;
	public static SoundEvent berspawn1;
	public static SoundEvent berspawn2;
	public static SoundEvent chaattaque1;
	public static SoundEvent chaattaque2;
	public static SoundEvent chaattaque3;
	public static SoundEvent chadouleur1;
	public static SoundEvent chadouleur2;
	public static SoundEvent chadouleur3;
	public static SoundEvent chadouleur4;
	public static SoundEvent chamort;
	public static SoundEvent charespawn1;
	public static SoundEvent chasaut;
	public static SoundEvent chaspawn1;
	public static SoundEvent chaspawn2;
	public static SoundEvent ingattaque1;
	public static SoundEvent ingattaque2;
	public static SoundEvent ingattaque3;
	public static SoundEvent ingdouleur1;
	public static SoundEvent ingdouleur2;
	public static SoundEvent ingdouleur3;
	public static SoundEvent ingdouleur4;
	public static SoundEvent ingmort;
	public static SoundEvent ingrespawn1;
	public static SoundEvent ingsaut;
	public static SoundEvent ingspawn1;
	public static SoundEvent ingspawn2;
	public static SoundEvent palattaque1;
	public static SoundEvent palattaque2;
	public static SoundEvent palattaque3;
	public static SoundEvent paldouleur1;
	public static SoundEvent paldouleur2;
	public static SoundEvent paldouleur3;
	public static SoundEvent paldouleur4;
	public static SoundEvent palmort;
	public static SoundEvent palrespawn1;
	public static SoundEvent palsaut;
	public static SoundEvent palspawn1;
	public static SoundEvent palspawn2;
	public static SoundEvent preattaque1;
	public static SoundEvent preattaque2;
	public static SoundEvent preattaque3;
	public static SoundEvent predouleur1;
	public static SoundEvent predouleur2;
	public static SoundEvent predouleur3;
	public static SoundEvent predouleur4;
	public static SoundEvent premort;
	public static SoundEvent prerespawn1;
	public static SoundEvent presaut;
	public static SoundEvent prespawn1;
	public static SoundEvent prespawn2;
	
	public static void registerSounds() {
		arcattaque1 = registerSound("ambient.arc.arcattaque1");
		arcattaque2 = registerSound("ambient.arc.arcattaque2");
		arcattaque3 = registerSound("ambient.arc.arcattaque3");
		arcdouleur1 = registerSound("ambient.arc.arcdouleur1");
		arcdouleur2 = registerSound("ambient.arc.arcdouleur2");
		arcdouleur3 = registerSound("ambient.arc.arcdouleur3");
		arcdouleur4 = registerSound("ambient.arc.arcdouleur4");
		arcmort = registerSound("ambient.arc.arcmort");
		arcrespawn1 = registerSound("ambient.arc.arcrespawn1");
		arcsaut = registerSound("ambient.arc.arcsaut");
		arcspawn1 = registerSound("ambient.arc.arcspawn1");
		arcspawn2 = registerSound("ambient.arc.arcspawn2");
		assattaque1 = registerSound("ambient.ass.assattaque1");
		assattaque2 = registerSound("ambient.ass.assattaque2");
		assattaque3 = registerSound("ambient.ass.assattaque3");
		assdouleur1 = registerSound("ambient.ass.assdouleur1");
		assdouleur2 = registerSound("ambient.ass.assdouleur2");
		assdouleur3 = registerSound("ambient.ass.assdouleur3");
		assdouleur4 = registerSound("ambient.ass.assdouleur4");
		assmort = registerSound("ambient.ass.assmort");
		assrespawn1 = registerSound("ambient.ass.assrespawn1");
		asssaut = registerSound("ambient.ass.asssaut");
		assspawn1 = registerSound("ambient.ass.assspawn1");
		assspawn2 = registerSound("ambient.ass.assspawn2");
		berattaque1 = registerSound("ambient.ber.berattaque1");
		berattaque2 = registerSound("ambient.ber.berattaque2");
		berattaque3 = registerSound("ambient.ber.berattaque3");
		berdouleur1 = registerSound("ambient.ber.berdouleur1");
		berdouleur2 = registerSound("ambient.ber.berdouleur2");
		berdouleur3 = registerSound("ambient.ber.berdouleur3");
		berdouleur4 = registerSound("ambient.ber.berdouleur4");
		bermort = registerSound("ambient.ber.bermort");
		berrespawn1 = registerSound("ambient.ber.berrespawn1");
		bersaut = registerSound("ambient.ber.bersaut");
		berspawn1 = registerSound("ambient.ber.berspawn1");
		berspawn2 = registerSound("ambient.ber.berspawn2");
		chaattaque1 = registerSound("ambient.cha.chaattaque1");
		chaattaque2 = registerSound("ambient.cha.chaattaque2");
		chaattaque3 = registerSound("ambient.cha.chaattaque3");
		chadouleur1 = registerSound("ambient.cha.chadouleur1");
		chadouleur2 = registerSound("ambient.cha.chadouleur2");
		chadouleur3 = registerSound("ambient.cha.chadouleur3");
		chadouleur4 = registerSound("ambient.cha.chadouleur4");
		chamort = registerSound("ambient.cha.chamort");
		charespawn1 = registerSound("ambient.cha.charespawn1");
		chasaut = registerSound("ambient.cha.chasaut");
		chaspawn1 = registerSound("ambient.cha.chaspawn1");
		chaspawn2 = registerSound("ambient.cha.chaspawn2");
		ingattaque1 = registerSound("ambient.ing.ingattaque1");
		ingattaque2 = registerSound("ambient.ing.ingattaque2");
		ingattaque3 = registerSound("ambient.ing.ingattaque3");
		ingdouleur1 = registerSound("ambient.ing.ingdouleur1");
		ingdouleur2 = registerSound("ambient.ing.ingdouleur2");
		ingdouleur3 = registerSound("ambient.ing.ingdouleur3");
		ingdouleur4 = registerSound("ambient.ing.ingdouleur4");
		ingmort = registerSound("ambient.ing.ingmort");
		ingrespawn1 = registerSound("ambient.ing.ingrespawn1");
		ingsaut = registerSound("ambient.ing.ingsaut");
		ingspawn1 = registerSound("ambient.ing.ingspawn1");
		ingspawn2 = registerSound("ambient.ing.ingspawn2");
		palattaque1 = registerSound("ambient.pal.palattaque1");
		palattaque2 = registerSound("ambient.pal.palattaque2");
		palattaque3 = registerSound("ambient.pal.palattaque3");
		paldouleur1 = registerSound("ambient.pal.paldouleur1");
		paldouleur2 = registerSound("ambient.pal.paldouleur2");
		paldouleur3 = registerSound("ambient.pal.paldouleur3");
		paldouleur4 = registerSound("ambient.pal.paldouleur4");
		palmort = registerSound("ambient.pal.palmort");
		palrespawn1 = registerSound("ambient.pal.palrespawn1");
		palsaut = registerSound("ambient.pal.palsaut");
		palspawn1 = registerSound("ambient.pal.palspawn1");
		palspawn2 = registerSound("ambient.pal.palspawn2");
		preattaque1 = registerSound("ambient.pre.preattaque1");
		preattaque2 = registerSound("ambient.pre.preattaque2");
		preattaque3 = registerSound("ambient.pre.preattaque3");
		predouleur1 = registerSound("ambient.pre.predouleur1");
		predouleur2 = registerSound("ambient.pre.predouleur2");
		predouleur3 = registerSound("ambient.pre.predouleur3");
		predouleur4 = registerSound("ambient.pre.predouleur4");
		premort = registerSound("ambient.pre.premort");
		prerespawn1 = registerSound("ambient.pre.prerespawn1");
		presaut = registerSound("ambient.pre.presaut");
		prespawn1 = registerSound("ambient.pre.prespawn1");
		prespawn2 = registerSound("ambient.pre.prespawn2");
	}
	
	public static SoundEvent registerSound(String name) {
		ResourceLocation loc = new ResourceLocation(References.MODID, name);
		SoundEvent e = new SoundEvent(loc);
		e.setRegistryName(name);
		ForgeRegistries.SOUND_EVENTS.register(e);
		return e;
	}

}
